version: '3.8'

x-php-common: &php-common
  image: php:8.2-apache
  mem_limit: 512m
  cpus: 0.5
  environment:
    PHP_OPCACHE_ENABLE: 1
    PHP_OPCACHE_MEMORY_CONSUMPTION: 128
    PHP_OPCACHE_INTERNED_STRINGS_BUFFER: 16
    PHP_OPCACHE_MAX_ACCELERATED_FILES: 10000
    PHP_OPCACHE_VALIDATE_TIMESTAMPS: 0
  networks:
    - webnet

services:
  site1:
    <<: *php-common
    volumes:
      - /home/web/site1:/var/www/html/
    deploy:
      replicas: 4

  site2:
    <<: *php-common
    volumes:
      - /home/web/site2:/var/www/html/
    deploy:
      replicas: 4

  haproxy:
    image: haproxy:2.5
    container_name: haproxy
    ports:
      - "80:80"
      - "443:443"
      - "8404:8404"
    volumes:
      - /home/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - /etc/letsencrypt/live/
      - /etc/letsencrypt/live/
    networks:
      - webnet
    mem_limit: 256m
    cpus: 0.5

networks:
  webnet:
    driver: bridge
